### PR TITLE
Bump 0.1.2

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by jakirkham** [comment]
Would be nice to add `license_file: LICENSE.txt` to `about` while we are at it. Though could be done as a follow-up as well.

**Comment by mrocklin** [comment]
Sure, done.

**Comment by mrocklin** [comment]
Is it now standard practice to add license_file to all recipes?

**Comment by jakirkham** [comment]
TL;DR Basically yes.

If there is a license file available, yes we have been trying to package it. If not, we have been pushing project developers to add a license. If it is a PyPI package, we try to have them include it in their `MANIFEST.in`. Once there is a license file available in a release, we try to package it as well. Though in some cases we have included the license file in the recipe to ensure we can package it.

**Pull request merged**
