### PR TITLE
bump version to 0.1.3

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by jakirkham** [comment]
We can also take this opportunity to convert this package to a [`noarch: python`]( http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages ) package. This will run on only CircleCI allowing it to build and deploy faster. The resulting packages can be installed anywhere with Python 2 or 3.

**Comment by mrocklin** [comment]
Is noarch now a standard practice on conda-forge?  It seems like many packages (in particular many of the dask packages) would possibly benefit from this.

**Comment by jakirkham** [comment]
Indeed. We have just started rolling it out and have converted a few packages over.

There are some caveats like selectors can't be used, which is a `conda`/`conda-build` limitation ATM. Though we would like to find solutions for those cases too.

**Comment by jakirkham** [comment]
Also needs another re-render after adding `noarch: python` as `conda-smithy` uses this to change the CI files.

**Comment by mrocklin** [comment]
I see.  Indeed.  That does look like it will use less CI resources :)

**Comment by jakirkham** [comment]
Yep. Looks good. Feel free to merge when you are ready.

**Comment by mrocklin** [comment]
Is rebase or squash typical in conda-forge?

**Comment by jakirkham** [comment]
Normally I just do merge commits. Some people like to see what version a feedstock was re-rendered with and merge commits allow one to see the latest commit on files to see what version of `conda-smithy` was used. Suppose rebasing would make this possible too. Have seen some use merge and squash.

We leave this pretty open as it really is up to the maintainers how they want to manage their repo's history.

**Pull request merged**
